### ISSUE TITLE
Cannot run VisEditor on Mac.

### ISSUE THREAD

**Issue by truonguit2010** [kotcrab/vis-editor#132]
Hi,
I cannot run VisEditor from source on Mac. How can I fix it?
```
[15:46][Debug] Loading completed
java.lang.IllegalStateException: Mouse doesn't support native cursors
	at org.lwjgl.input.Mouse.setNativeCursor(Mouse.java:186)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setSystemCursor(LwjglGraphics.java:633)
	at com.kotcrab.vis.ui.widget.LinkLabel$1.enter(LinkLabel.java:107)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:68)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
	at com.badlogic.gdx.scenes.scene2d.Stage.fireEnterAndExit(Stage.java:252)
	at com.badlogic.gdx.scenes.scene2d.Stage.act(Stage.java:215)
	at com.kotcrab.vis.editor.Editor.render(Editor.java:250)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:242)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[15:46][Fatal] java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
	at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
	at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:194)
	at com.kotcrab.vis.ui.widget.color.internal.PickerCommons.dispose(PickerCommons.java:103)
	at com.kotcrab.vis.ui.widget.color.BasicColorPicker.dispose(BasicColorPicker.java:310)
	at com.kotcrab.vis.ui.widget.color.ColorPicker.dispose(ColorPicker.java:148)
	at com.kotcrab.vis.editor.module.editor.ColorPickerModule.dispose(ColorPickerModule.java:35)
	at com.kotcrab.vis.editor.module.ModuleContainer.dispose(ModuleContainer.java:189)
	at com.kotcrab.vis.editor.Editor.dispose(Editor.java:259)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:311)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

[15:46][Fatal] Uncaught exception occurred, error report will be saved
```

**Comment by intrigus** [comment]
That's a known bug and should be fixed in libgdx itself.

**Comment by kotcrab** [comment]
In the meantime you can run from source on the lwjgl3 branch: https://github.com/kotcrab/VisEditor/wiki/Building-Vis-From-Source#launching-viseditor-from-command-line

**Comment by kotcrab** [comment]
Editor snapshot binary with this fix can be downloaded from here: https://dl.kotcrab.com/vis/editor/edge/VisEditor-edge-20160312-1.zip
