### ISSUE TITLE
Error at open project without folder gfx

### ISSUE THREAD

**Issue by vzlomvl** [kotcrab/vis-editor#184]
Can't open project without folder assets\gfx. On load project shows the error http://prnt.sc/b5cenw.
```
[04:11][Info] Build: 20160517-2
[04:11][Debug] Starting loading
[04:11][Debug] VisUI 1.0.2 loaded
[04:11][Debug][PluginLoader] Loading plugins from: D:/Projects/VisEditor-0.3.2-SNAPSHOT/plugins
[04:11][Debug][PluginLoader] Loading: spine
[04:11][Debug][PluginLoader] Loading: spine-notifier
[04:11][Debug][ExtensionStorage::ResourceLoader] Loading SpinePluginAssets
[04:11][Debug] Twitter cache is up to date
[04:11][Debug][EditorModuleContainer] Init took: 494 ms
[04:11][Debug] Loading completed
[04:11][Info][UpdateChecker] No updates found
[04:11][Debug][AsyncTask::ProjectLoaderThread] Loading project data...
[04:11][Debug][AsyncTask::ProjectLoaderThread] Initializing...
[04:11][Fatal] java.lang.IllegalStateException: Folder must be directory!
	at com.kotcrab.vis.editor.util.FileUtils.streamFilesRecursively(FileUtils.java:148)
	at com.kotcrab.vis.editor.module.project.TextureNameCheckerModule.init(TextureNameCheckerModule.java:42)
	at com.kotcrab.vis.editor.module.ModuleContainer.init(ModuleContainer.java:80)
	at com.kotcrab.vis.editor.Editor$8.lambda$execute$107(Editor.java:417)
	at com.kotcrab.vis.editor.util.async.AsyncTask.lambda$executeOnOpenGL$103(AsyncTask.java:82)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:141)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
	at com.kotcrab.vis.editor.Main.main(Main.java:96)

[04:11][Error][TextureCacheModule] Texture cache not ready, probably they aren't any textures in project or packer failed
[04:11][Debug][ExtensionStorage::ResourceLoader] Unloading SpinePluginAssets
[04:11][Fatal] java.lang.NullPointerException
	at com.kotcrab.vis.editor.module.editor.InputModule.removeListener(InputModule.java:48)
	at com.kotcrab.vis.editor.module.project.ExportersManagerModule.dispose(ExportersManagerModule.java:94)
	at com.kotcrab.vis.editor.module.ModuleContainer.dispose(ModuleContainer.java:189)
	at com.kotcrab.vis.editor.Editor.dispose(Editor.java:258)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.dispose(Lwjgl3Window.java:281)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.cleanup(Lwjgl3Application.java:153)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:104)
	at com.kotcrab.vis.editor.Main.main(Main.java:96)

[04:11][Fatal] Uncaught exception occurred, error report will be saved
```

**Comment by kotcrab** [comment]
Fixed, thanks.
