### ISSUE TITLE
Error on create spine(last version 3.2.0) object.

### ISSUE THREAD

**Issue by vzlomvl** [kotcrab/vis-editor#189]
When i try add spine animation to scene, i get this error. This may be due to the fact that I use the latest version of the spine 3.2.0
```
[13:18][Debug] Starting loading
[13:18][Debug] VisUI 1.1.2 loaded
[13:18][Debug][PluginLoader] Loading plugins from: D:/VisEditor-0.3.2-SNAPSHOT/plugins
[13:18][Debug][PluginLoader] Loading: spine
[13:18][Debug][PluginLoader] Loading: spine-notifier
[13:18][Debug][ExtensionStorage::ResourceLoader] Loading SpinePluginAssets
[13:18][Debug] Twitter cache is up to date
[13:18][Debug][EditorModuleContainer] Init took: 486 ms
[13:18][Debug] Loading completed
[13:18][Info][UpdateChecker] No updates found
[13:18][Debug][AsyncTask::ProjectLoaderThread] Loading project data...
[13:18][Debug][AsyncTask::ProjectLoaderThread] Initializing...
[13:18][Debug][ProjectModuleContainer] Init took: 627 ms
[13:18][Debug][SceneModuleContainer] Init took: 164 ms
[13:18][Debug][SceneModuleContainer] Populating EntityEngine
[13:18][Debug][ExtensionStorage::ResourceLoader] Unloading SpinePluginAssets
[13:18][Fatal] java.lang.IllegalArgumentException: No enum constant com.esotericsoftware.spine.attachments.AttachmentType.weightedmesh
	at java.lang.Enum.valueOf(Unknown Source)
	at com.esotericsoftware.spine.attachments.AttachmentType.valueOf(AttachmentType.java:34)
	at com.esotericsoftware.spine.SkeletonJson.readAttachment(SkeletonJson.java:188)
	at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:153)
	at com.kotcrab.vis.plugin.spine.SpineCacheModule$SkeletonCache.getData(SpineCacheModule.java:112)
	at com.kotcrab.vis.plugin.spine.SpineCacheModule.get(SpineCacheModule.java:78)
	at com.kotcrab.vis.plugin.spine.SpineCacheModule.get(SpineCacheModule.java:64)
	at com.kotcrab.vis.plugin.spine.SpineCacheModule.get(SpineCacheModule.java:60)
	at com.kotcrab.vis.plugin.spine.SpineEditorSupport.processDropPayload(SpineEditorSupport.java:114)
	at com.kotcrab.vis.editor.module.scene.entitymanipulator.EntityManipulatorModule.processDropPayload(EntityManipulatorModule.java:485)
	at com.kotcrab.vis.editor.ui.scene.SceneTab$1.drop(SceneTab.java:178)
	at com.kotcrab.vis.editor.util.scene2d.VisDragAndDrop$1.dragStop(VisDragAndDrop.java:198)
	at com.badlogic.gdx.scenes.scene2d.utils.DragListener.touchUp(DragListener.java:64)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:81)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:198)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:254)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
	at com.kotcrab.vis.editor.Main.main(Main.java:96)

[13:18][Fatal] Uncaught exception occurred, error report will be saved
```

**Comment by kotcrab** [comment]
I've updated the spine runtime, should work now.
