### ISSUE TITLE
Crash on OSX when moving cursor over button

### ISSUE THREAD

**Issue by raulpiiber** [kotcrab/vis-editor#190]
Vis-editor 0.3.1 closes on mac when I move cursor over some button. I am using java version "1.8.0_65".

13:18][Fatal] java.lang.IllegalStateException: No match found
	at java.util.regex.Matcher.group(Matcher.java:536)
	at java.util.regex.Matcher.group(Matcher.java:496)
	at com.kotcrab.vis.editor.module.editor.UpdateCheckerModule.lambda$getReleases$257(UpdateCheckerModule.java:123)
	at java.lang.Thread.run(Thread.java:745)

java.lang.IllegalStateException: Mouse doesn't support native cursors
	at org.lwjgl.input.Mouse.setNativeCursor(Mouse.java:186)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setSystemCursor(LwjglGraphics.java:633)
	at com.kotcrab.vis.ui.widget.LinkLabel$1.enter(LinkLabel.java:107)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:68)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
	at com.badlogic.gdx.scenes.scene2d.Stage.fireEnterAndExit(Stage.java:252)
	at com.badlogic.gdx.scenes.scene2d.Stage.act(Stage.java:220)
	at com.kotcrab.vis.editor.Editor.render(Editor.java:249)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:242)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[13:18][Fatal] java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glDeleteTextures(GL11.java:732)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glDeleteTexture(LwjglGL20.java:248)
	at com.badlogic.gdx.graphics.GLTexture.delete(GLTexture.java:170)
	at com.badlogic.gdx.graphics.Texture.dispose(Texture.java:194)
	at com.kotcrab.vis.ui.widget.color.internal.PickerCommons.dispose(PickerCommons.java:103)
	at com.kotcrab.vis.ui.widget.color.BasicColorPicker.dispose(BasicColorPicker.java:310)
	at com.kotcrab.vis.ui.widget.color.ColorPicker.dispose(ColorPicker.java:148)
	at com.kotcrab.vis.editor.module.editor.ColorPickerModule.dispose(ColorPickerModule.java:35)
	at com.kotcrab.vis.editor.module.ModuleContainer.dispose(ModuleContainer.java:191)
	at com.kotcrab.vis.editor.Editor.dispose(Editor.java:258)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$4.run(LwjglCanvas.java:311)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by kotcrab** [comment]
This is already fixed in 0.3.2 which I'll be releasing today.

**Comment by kotcrab** [comment]
You can now download 0.3.2 from VisEditor website.

**Comment by raulpiiber** [comment]
Thanks, it's working now.
