### ISSUE TITLE
Field not found: textureAtlasPath

### ISSUE THREAD

**Issue by raulpiiber** [kotcrab/vis-editor#192]
I created new project, created scene, added few images and exported assets. When loading that scene in libGDX app exception is thrown. 

libGDX 1.9.3
VisEditor 0.3.2

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load dependencies of asset: scene/firstScene.scene
	at com.badlogic.gdx.assets.AssetManager.handleTaskError(AssetManager.java:570)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:375)
	at com.badlogic.gdx.assets.AssetManager.finishLoading(AssetManager.java:396)
	at com.kotcrab.vis.runtime.scene.VisAssetManager.loadSceneNow(VisAssetManager.java:81)
	at com.kotcrab.vis.runtime.scene.VisAssetManager.loadSceneNow(VisAssetManager.java:76)
	at com.test.app.ExampleVis.create(ExampleVis.java:29)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load dependencies of asset: scene/firstScene.scene
	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:121)
	at com.badlogic.gdx.assets.AssetLoadingTask.update(AssetLoadingTask.java:90)
	at com.badlogic.gdx.assets.AssetManager.updateTask(AssetManager.java:498)
	at com.badlogic.gdx.assets.AssetManager.update(AssetManager.java:373)
	... 6 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.SerializationException: Error reading file: scene/firstScene.scene
	at com.badlogic.gdx.utils.async.AsyncResult.get(AsyncResult.java:46)
	at com.badlogic.gdx.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:119)
	... 9 more
Caused by: com.badlogic.gdx.utils.SerializationException: Error reading file: scene/firstScene.scene
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:694)
	at com.kotcrab.vis.runtime.scene.SceneLoader.getDependencies(SceneLoader.java:115)
	at com.kotcrab.vis.runtime.scene.SceneLoader.getDependencies(SceneLoader.java:58)
	at com.badlogic.gdx.assets.AssetLoadingTask.call(AssetLoadingTask.java:64)
	at com.badlogic.gdx.assets.AssetLoadingTask.call(AssetLoadingTask.java:34)
	at com.badlogic.gdx.utils.async.AsyncExecutor$2.call(AsyncExecutor.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.badlogic.gdx.utils.SerializationException: Field not found: textureAtlasPath (com.kotcrab.vis.runtime.data.SceneData)
Serialization trace:
{}.textureAtlasPath
	at com.badlogic.gdx.utils.Json.readFields(Json.java:790)
	at com.badlogic.gdx.utils.Json.readValue(Json.java:919)
	at com.badlogic.gdx.utils.Json.fromJson(Json.java:692)

**Comment by kotcrab** [comment]
Looks like you are using wrong runtime version. Check your `build.gradle` file and make sure it matches editor version (0.3.2). More info https://github.com/kotcrab/vis-editor/wiki/LibGDX-Project-Setup

**Comment by raulpiiber** [comment]
Yes, I had wrong runtime, thanks!
