### ISSUE TITLE
BACKSPACE on TextField crashes after TextField loses focus

### ISSUE THREAD

**Issue by LakeIshikawa** [kotcrab/vis-editor#207]
There appears to be a problem with the TextField after it loses and re-gain focus, when backspace is pressed an exception is generated:

Exception in thread "LWJGL Application" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1931)
	at com.kotcrab.vis.ui.widget.VisTextField$TextFieldClickListener.keyTyped(VisTextField.java:1206)

The "cursor" field looks to be bigger than the actual word in the textfield.

**Comment by kotcrab** [comment]
What version of VisUI are you using, can you reproduce with latest 1.1.5? Please tell exact steps to reproduce this. This doesn't work:
1. Open VisUI test app
2. Click on text field with "textbox" text, placing cursor at text end
3. Remove everything using backspace
4. Click on some button to make text field lost focus
5. Click on same text field again
6. Press backspace, app doesn't crash

**Comment by Snehks** [comment]
I have encountered the sam bug but the way to produce it is as follows.

1. Type something on the field.
2. Select all in the text field
3. Now remove focus, i.e. click on some other UI element or a text box.
4. Go back to the original text field and then click backspace.
BOOM! Crashes.

Stack trace 

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1931)
	at com.kotcrab.vis.ui.widget.VisTextField$TextFieldClickListener.keyTyped(VisTextField.java:1206)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:49)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
	at com.badlogic.gdx.scenes.scene2d.Stage.keyTyped(Stage.java:445)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:318)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

**Comment by kotcrab** [comment]
Thanks for reproduction steps @Snehks. For some reason I could only reproduce when using LWJGL backend. I fixed it.
