### ISSUE TITLE
Enabling Spine Plugin -> crash

### ISSUE THREAD

**Issue by Silvest89** [kotcrab/vis-editor#236]
So I just downloaded VisEditor(0.3.4) and everytime I click on the checkbox the VisEditor crashes.

```
--- VisEditor Crash Report ---
VisEditor 0.3.4
VersionCode: 24 Snapshot: false

Java: 1.8.0_92 Oracle Corporation
Java VM: Java HotSpot(TM) 64-Bit Server VM
OS: Windows 10 10.0 amd64

--- Log file ---
[10:52][Warning][App] UTF-8 is not default charset, trying to change...
[10:52][Warning][App] Charset change successful, run with VM argument: -Dfile.encoding=UTF-8 to avoid this.
[10:52][Info] Build: not built using CI
[10:52][Debug] Starting loading
[10:52][Debug] VisUI 1.2.4 loaded
[10:52][Debug][PluginLoader] Loading plugins from: C:/Users/johnn/Desktop/VisEditor-0.3.4/plugins
[10:52][Debug][PluginLoader] Skipping: spine
[10:52][Debug][PluginLoader] Skipping: spriter
[10:52][Debug][PluginLoader] Loading: spine-notifier
[10:52][Debug] Reloading Twitter cache
[10:52][Info][UpdateChecker] Update check skipped
[10:52][Debug][EditorModuleContainer] Init took: 337 ms
[10:52][Debug] Loading completed
[10:55][Fatal] java.lang.ArrayIndexOutOfBoundsException: 6000
	at com.badlogic.gdx.graphics.g2d.PolygonSpriteBatch.draw(PolygonSpriteBatch.java:763)
	at com.badlogic.gdx.graphics.g2d.BitmapFontCache.draw(BitmapFontCache.java:237)
	at com.badlogic.gdx.scenes.scene2d.ui.Label.draw(Label.java:218)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.draw(ScrollPane.java:588)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:123)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:163)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:119)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:110)
	at com.badlogic.gdx.scenes.scene2d.ui.Window.draw(Window.java:243)
	at com.kotcrab.vis.ui.widget.VisWindow.draw(VisWindow.java:239)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
	at com.kotcrab.vis.editor.Editor.render(Editor.java:253)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:252)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:127)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:97)
	at com.kotcrab.vis.editor.Main.main(Main.java:97)
```

**Comment by kotcrab** [comment]
This was fixed in latest snapshot.
