### ISSUE TITLE
Crash on KDE Neon 5.9 platform when clicking on "Show Log"

### ISSUE THREAD

**Issue by ravisharma1987** [kotcrab/vis-editor#248]
Version: 4.0 SNAPSHOT: 
Reproduce: 
1. Open Editor
2. Open a project
3. Click on Show log from the menu

Observation: Editor crashes
Repeatability: Always/Every time

Stacktrace printed on console. 
[20:18][Fatal] java.lang.UnsupportedOperationException: The EDIT action is not supported on the current platform!
        at java.awt.Desktop.checkActionSupport(Desktop.java:225)
        at java.awt.Desktop.edit(Desktop.java:300)
        at com.kotcrab.vis.editor.util.FileUtils.open(FileUtils.java:67)
        at com.kotcrab.vis.editor.module.editor.MenuBarModule.lambda$createHelpMenu$100(MenuBarModule.java:175)
        at com.kotcrab.vis.editor.util.scene2d.MenuUtils$1.changed(MenuUtils.java:53)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:123)
        at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:91)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
        at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:81)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Input.update(Lwjgl3Input.java:198)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:257)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:138)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:107)
        at com.kotcrab.vis.editor.Main.main(Main.java:97)

**Comment by ravisharma1987** [comment]
I checked out viseditor code and searched for the issue. 
Seems like the open function in the com.kotcrab.vis.editor.util.FileUtils.java doesn't check for supported Desktop operation and directly calls Desktop.getDesktop().edit(file.file());

Desktop API support for linux is mostly based on gtk libraries and hence on KDE Neon it is unsupported. 
So, I fixed it myself. 

Here is the new function: 

public static void open (FileHandle file) {
		try {
			if (OsUtils.isMac()) {
				Runtime.getRuntime().exec("open " + file.path()); //see #123
			} else if(Desktop.isDesktopSupported()) {
				Desktop desktop = Desktop.getDesktop();

				if (desktop.isSupported(Desktop.Action.EDIT))
					Desktop.getDesktop().edit(file.file());
				else if (desktop.isSupported(Desktop.Action.OPEN))
					Desktop.getDesktop().open(file.file());
			}
		} catch (IOException e) {
			Log.exception(e);
		}
	}
