### ISSUE TITLE
How can we make X4 and X8 ui ?

### ISSUE THREAD

**Issue by eix128** [kotcrab/vis-editor#265]
what steps required for X4 and X8 ui ?
We can scale for you.
We also need for Android and IOS
If you can help we can update assets-raw for you also

**Comment by kotcrab** [comment]
The process is quite involved. You have to first export new elements from vector svg file. For some it's as simple as exporting with bigger size, some has to be manually adjusted for bigger size. Then you export two fonts sizes using Hiero. Then you have to define skin definition in json. Simplest way to do it is to use stock USL definition and define new `com.kotcrab.vis.ui.Sizes` for new size.

If you want to do it then feel free to go for it. However I won't be accepting this back into core project as explained in #226.

**Comment by eix128** [comment]
We can donate your project for X4 and X8.
We still cannot find any way to make X4 , there is no documentation ?

**Comment by eix128** [comment]
We have added 
C:\Works\vis-editor-master\ui\assets-raw\x4
with all png files , then

on build.gradle file
we patched 
task packSkin << {
    description 'Compiles VisUI USL skin to JSON'

    def basePath = rootProject.projectDir.absolutePath + "/ui/"

    def x1Input = new File(basePath + "assets-raw/x1").absolutePath
    def x1Output = new File(basePath + "src/main/resources/com/kotcrab/vis/ui/skin/x1/").absolutePath
    com.badlogic.gdx.tools.texturepacker.TexturePacker.process(x1Input, x1Output, "uiskin")
    def x2Input = new File(basePath + "assets-raw/x2").absolutePath
    def x2Output = new File(basePath + "src/main/resources/com/kotcrab/vis/ui/skin/x2/").absolutePath
    com.badlogic.gdx.tools.texturepacker.TexturePacker.process(x2Input, x2Output, "uiskin")

    def x4Input = new File(basePath + "assets-raw/x4").absolutePath
    def x4Output = new File(basePath + "src/main/resources/com/kotcrab/vis/ui/skin/x4/").absolutePath
    com.badlogic.gdx.tools.texturepacker.TexturePacker.process(x4Input, x4Output, "uiskin")
}

task compileUsl << {
    description 'Pack skin textures into texture atlases'

    def basePath = rootProject.projectDir.absolutePath + "/ui/src/main/resources/com/kotcrab/vis/ui/skin/"
    def x1File = new File(basePath + "x1/uiskin.json")
    def x2File = new File(basePath + "x2/uiskin.json")
    def x4File = new File(basePath + "x4/uiskin.json")
    com.kotcrab.vis.usl.Lexer.addIncludeSource(rootProject.projectDir.absolutePath + "/usl/styles")
    def json = com.kotcrab.vis.usl.USL.parse(null, "include <visui-" + version + ">")
    x1File.text = json
    x2File.text = json
    x4File.text = json
}

task compileSkin(dependsOn: ['compileUsl', 'packSkin']) {
    description 'Pack skin textures into texture atlases and compile USL into JSON'
}


after i tried 



C:\Works\vis-editor-master>gradlew --stacktrace  --info compileSkin
Initialized native services in: C:\Users\kadir\.gradle\native
Connected to daemon DaemonInfo{pid=4188, address=[631f95dc-5e34-4402-af99-f069f920986e port:50202, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], state=Idle, lastBusy=1504918247971, context=DefaultDaemonContext[uid=224d5e62-9445-416d-8d65-68fb2c1beee2,javaHome=C:\Tools\JDK8_u131\x64,daemonRegistryDir=C:\Users\kadir\.gradle\daemon,pid=4188,idleTimeout=10800000,daemonOpts=-Xms256m,-Xmx1024m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]}. Dispatching request Build{id=97cbac35-177e-4a49-bc2f-44d3449f1619.1, currentDir=C:\Works\vis-editor-master}.
Received result org.gradle.launcher.daemon.protocol.BuildStarted@35432107 from daemon DaemonInfo{pid=4188, address=[631f95dc-5e34-4402-af99-f069f920986e port:50202, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], state=Idle, lastBusy=1504918247971, context=DefaultDaemonContext[uid=224d5e62-9445-416d-8d65-68fb2c1beee2,javaHome=C:\Tools\JDK8_u131\x64,daemonRegistryDir=C:\Users\kadir\.gradle\daemon,pid=4188,idleTimeout=10800000,daemonOpts=-Xms256m,-Xmx1024m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be starting).
The client will now receive all logging from the daemon (pid: 4188). The daemon log file: C:\Users\kadir\.gradle\daemon\3.5\daemon-4188.out.log
Starting 2nd build in daemon [uptime: 35.296 secs, performance: 96%, no major garbage collections]
Executing build with daemon context: DefaultDaemonContext[uid=224d5e62-9445-416d-8d65-68fb2c1beee2,javaHome=C:\Tools\JDK8_u131\x64,daemonRegistryDir=C:\Users\kadir\.gradle\daemon,pid=4188,idleTimeout=10800000,daemonOpts=-Xms256m,-Xmx1024m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]
Creating new cache for plugin-use-metadata, path C:\Users\kadir\.gradle\caches\3.5\plugin-resolution\plugin-use-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@1a75dce3
Creating new cache for client-status, path C:\Users\kadir\.gradle\caches\3.5\plugin-resolution\client-status.bin, access org.gradle.cache.internal.DefaultCacheAccess@1a75dce3
Starting Build
Settings evaluated using settings file 'C:\Works\vis-editor-master\settings.gradle'.
Projects loaded. Root project using build file 'C:\Works\vis-editor-master\build.gradle'.
Included projects: [root project 'vis-ui', project ':ui', project ':usl']
Configuration on demand is an incubating feature.
Evaluating root project 'vis-ui' using build file 'C:\Works\vis-editor-master\build.gradle'.
Creating new cache for metadata-2.23/module-metadata, path C:\Users\kadir\.gradle\caches\modules-2\metadata-2.23\module-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@3f1cb6c6
Creating new cache for metadata-2.23/artifact-at-repository, path C:\Users\kadir\.gradle\caches\modules-2\metadata-2.23\artifact-at-repository.bin, access org.gradle.cache.internal.DefaultCacheAccess@3f1cb6c6
Creating new cache for fileHashes, path C:\Works\vis-editor-master\.gradle\3.5\taskHistory\fileHashes.bin, access org.gradle.cache.internal.DefaultCacheAccess@383e9de
Using 12 worker leases.
Evaluating project ':ui' using build file 'C:\Works\vis-editor-master\ui\build.gradle'.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at org.gradle.api.internal.AbstractTask.leftShift(AbstractTask.java:568)
        at org.gradle.api.Task$leftShift$0.call(Unknown Source)
        at build_dypyg7itpqgx5ukgo197ehb9t.run(C:\Works\vis-editor-master\ui\build.gradle:56)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:176)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:181)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:70)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:648)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:126)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:100)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:81)
        at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:42)
        at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$000(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.proceed(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:36)
        at org.gradle.initialization.DefaultGradleLauncher$CalculateTaskGraphAction.execute(DefaultGradleLauncher.java:220)
        at org.gradle.initialization.DefaultGradleLauncher$CalculateTaskGraphAction.execute(DefaultGradleLauncher.java:217)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:158)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:112)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:95)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Evaluating project ':usl' using build file 'C:\Works\vis-editor-master\usl\build.gradle'.
Selected primary task 'compileSkin' from project :
All projects evaluated.
Tasks to be executed: [task ':ui:compileUsl', task ':ui:packSkin', task ':ui:compileSkin']
Creating new cache for jvmClassSignatures, path C:\Works\vis-editor-master\.gradle\3.5\taskHistory\jvmClassSignatures.bin, access org.gradle.cache.internal.DefaultCacheAccess@383e9de
Creating new cache for fileSnapshots, path C:\Works\vis-editor-master\.gradle\3.5\taskHistory\fileSnapshots.bin, access org.gradle.cache.internal.DefaultCacheAccess@383e9de
Creating new cache for taskHistory, path C:\Works\vis-editor-master\.gradle\3.5\taskHistory\taskHistory.bin, access org.gradle.cache.internal.DefaultCacheAccess@383e9de
:ui:compileUsl (Thread[Daemon worker,5,main]) started.
:ui:compileUsl
Putting task artifact state for task ':ui:compileUsl' into context took 0.0 secs.
Executing task ':ui:compileUsl' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:ui:compileUsl (Thread[Daemon worker,5,main]) completed. Took 0.03 secs.
:ui:packSkin (Thread[Daemon worker,5,main]) started.
:ui:packSkin
Putting task artifact state for task ':ui:packSkin' into context took 0.0 secs.
Executing task ':ui:packSkin' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
x1
button-down (alias of button-blue)
menu-bg (alias of grey)
textfield (alias of check-off)
tree-over (alias of separator)
vis-blue (alias of list-selection)
vis-check (alias of check-off)
vis-check-over (alias of textfield-over)
window-bg (alias of select-box-list-bg)
Packing.........
Writing 512x256: C:\Works\vis-editor-master\ui\src\main\resources\com\kotcrab\vis\ui\skin\x1\uiskin.png
x2
button-down (alias of button-blue)
menu-bg (alias of grey)
textfield (alias of check-off)
tree-over (alias of separator)
vis-blue (alias of list-selection)
vis-check (alias of check-off)
vis-check-over (alias of textfield-over)
vis-radio (alias of radio-off)
window-bg (alias of select-box-list-bg)
Packing.........
Writing 1024x512: C:\Works\vis-editor-master\ui\src\main\resources\com\kotcrab\vis\ui\skin\x2\uiskin.png
x4
:ui:packSkin FAILED
:ui:packSkin (Thread[Daemon worker,5,main]) completed. Took 1.288 secs.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Works\vis-editor-master\ui\build.gradle' line: 70

* What went wrong:
Execution failed for task ':ui:packSkin'.
> Error packing images.

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ui:packSkin'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:98)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:68)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:230)
        at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:227)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:161)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:112)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:95)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: java.lang.RuntimeException: Error packing images.
        at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:635)
        at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:618)
        at com.badlogic.gdx.tools.texturepacker.TexturePacker$process.call(Unknown Source)
        at build_dypyg7itpqgx5ukgo197ehb9t$_run_closure6.doCall(C:\Works\vis-editor-master\ui\build.gradle:70)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:656)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:637)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:90)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:86)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
        ... 70 more
Caused by: java.lang.Exception: Error processing directory: C:\Works\vis-editor-master\ui\assets-raw\x4
        at com.badlogic.gdx.tools.FileProcessor.process(FileProcessor.java:157)
        at com.badlogic.gdx.tools.texturepacker.TexturePackerFileProcessor.process(TexturePackerFileProcessor.java:143)
        at com.badlogic.gdx.tools.FileProcessor.process(FileProcessor.java:121)
        at com.badlogic.gdx.tools.texturepacker.TexturePackerFileProcessor.process(TexturePackerFileProcessor.java:97)
        at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:633)
        ... 84 more
Caused by: java.lang.RuntimeException: Invalid button-blue-down ninepatch split pixel at 0, 0, rgba: 0, 120, 179, 1
        at com.badlogic.gdx.tools.texturepacker.ImageProcessor.splitError(ImageProcessor.java:266)
        at com.badlogic.gdx.tools.texturepacker.ImageProcessor.getSplitPoint(ImageProcessor.java:403)
        at com.badlogic.gdx.tools.texturepacker.ImageProcessor.getSplits(ImageProcessor.java:276)
        at com.badlogic.gdx.tools.texturepacker.ImageProcessor.processImage(ImageProcessor.java:147)
        at com.badlogic.gdx.tools.texturepacker.ImageProcessor.addImage(ImageProcessor.java:94)
        at com.badlogic.gdx.tools.texturepacker.ImageProcessor.addImage(ImageProcessor.java:87)
        at com.badlogic.gdx.tools.texturepacker.TexturePacker.pack(TexturePacker.java:101)
        at com.badlogic.gdx.tools.texturepacker.TexturePackerFileProcessor.processDir(TexturePackerFileProcessor.java:218)
        at com.badlogic.gdx.tools.FileProcessor.process(FileProcessor.java:155)
        ... 88 more


BUILD FAILED

Total time: 2.459 secs
Stopped 0 worker daemon(s).
Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Build file 'C:\Works\vis-editor-master\ui\build.gradle' line: 70
Execution failed for task ':ui:packSkin'.] from daemon DaemonInfo{pid=4188, address=[631f95dc-5e34-4402-af99-f069f920986e port:50202, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], state=Idle, lastBusy=1504918247971, context=DefaultDaemonContext[uid=224d5e62-9445-416d-8d65-68fb2c1beee2,javaHome=C:\Tools\JDK8_u131\x64,daemonRegistryDir=C:\Users\kadir\.gradle\daemon,pid=4188,idleTimeout=10800000,daemonOpts=-Xms256m,-Xmx1024m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).

**Comment by eix128** [comment]
How to fix this issue ?

**Comment by eix128** [comment]
Caused by: java.lang.RuntimeException: Invalid button-blue-down ninepatch split pixel at 0, 0, rgba: 0, 120, 179, 1

**Comment by kotcrab** [comment]
> We can donate your project for X4 and X8.

I said before already I do not want it.
Reasons listed in previous issue. https://github.com/kotcrab/vis-editor/issues/226#issuecomment-254064819

> We still cannot find any way to make X4 , there is no documentation ?

Explained that too. https://github.com/kotcrab/vis-editor/issues/265#issuecomment-326971713

Your error is caused by not properly scaling ninepatch image. They have to have one pixel border.
This affects their scaling. Read [libgdx docs](https://github.com/libgdx/libgdx/wiki/Ninepatches) about them.

I'll allow myself to remove useless logs.
