### ISSUE TITLE
IllegalArgumentException in VisTextField

### ISSUE THREAD

**Issue by Snehks** [kotcrab/vis-editor#273]
Here is the stack trace to near to impossible to reproduce scenario. Basically somehow my game crashed and this is all I got. I have no idea how it happened and it happened to me for the first time in 4 months.

`java.lang.IllegalArgumentException: cursorPosition must be >= 0
	at com.kotcrab.vis.ui.widget.VisTextField.setCursorPosition(VisTextField.java:767)
	at com.kotcrab.vis.ui.widget.VisTextField$TextFieldClickListener.keyDown(VisTextField.java:1091)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:45)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:147)
	at com.badlogic.gdx.scenes.scene2d.Stage.keyDown(Stage.java:417)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:312)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
`

**Comment by kotcrab** [comment]
Not much I can do without reproduction steps. First thing I would check on your end is if you are modifying text field from another thread.
I see this happens during undo when cursor position should be changed to the last one. I can add clamp there so this exception will not happen again.

**Comment by kotcrab** [comment]
Done, thanks for reporting.
