### ISSUE TITLE
crashes on android (NoClassDefFoundError: Failed resolution of: Lcom/kotcrab/vis/ui/VisUI)

### ISSUE THREAD

**Issue by TypeOverride** [kotcrab/vis-editor#276]
on desktop it is working. How to fix it?

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/kotcrab/vis/ui/VisUI;
                                                                at com.myapp.screens.BaseGame.create(BaseGame.java:116)
                                                                at com.myapp.screens.BaseApp.create(BaseApp.java:66)
                                                                at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:311)
                                                                at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520)
                                                                at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
                                                             Caused by: java.lang.ClassNotFoundException: Didn't find class "com.kotcrab.vis.ui.VisUI" on path: DexPathList[[zip file "/data/app/com.myapp-2/base.apk", zip file "/data/app/com.myapp-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.myapp-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.myapp-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.myapp-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.myapp-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.myapp-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.myapp-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.myapp-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.myapp-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.myapp-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.myapp-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.myapp-2/lib/arm, /vendor/lib, /system/lib]]
                                                                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                at com.myapp.screens.BaseGame.create(BaseGame.java:116) 
                                                                at com.myapp.screens.BaseApp.create(BaseApp.java:66) 
                                                                at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:311) 
                                                                at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520) 
                                                                at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248) 
                                                            	Suppressed: java.lang.ClassNotFoundException: com.kotcrab.vis.ui.VisUI
                                                                at java.lang.Class.classForName(Native Method)
                                                                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                		... 6 more
                                                             Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available`

**Comment by kotcrab** [comment]
Looks like it's a problem with your build config, not a VisUI issue. If you think this is a VisUI issue please provide example project and steps how to build it so this can be reproduced.
