### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/kotcrab/vis/ui/VisUI (only android)

### ISSUE THREAD

**Issue by TypeOverride** [kotcrab/vis-editor#281]
I have this issue. On desktop it is working, on android he is runtime crashing.

It happens on line VisUI.load();

`E/AndroidRuntime: FATAL EXCEPTION: GLThread 21118
                  Process: com.lusche, PID: 5448
                  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/kotcrab/vis/ui/VisUI;
                      at com.lusche.screens.BaseGame.create(BaseGame.java:118)
                      at com.lusche.screens.BaseApp.create(BaseApp.java:64)
                      at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:311)
                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520)
                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.kotcrab.vis.ui.VisUI" on path: DexPathList[[zip file "/data/app/com.lusche-2/base.apk", zip file "/data/app/com.lusche-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.lusche-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.lusche-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.lusche-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.lusche-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.lusche-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.lusche-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.lusche-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.lusche-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.lusche-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.lusche-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.lusche-2/lib/arm, /vendor/lib, /system/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                      at com.lusche.screens.BaseGame.create(BaseGame.java:118) 
                      at com.lusche.screens.BaseApp.create(BaseApp.java:64) 
                      at com.badlogic.gdx.backends.android.AndroidGraphics.onSurfaceChanged(AndroidGraphics.java:311) 
                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520) 
                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248) 
                  	Suppressed: java.lang.ClassNotFoundException: com.kotcrab.vis.ui.VisUI
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                      		... 6 more
                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available`

build.gradle (application level):

> allprojects {
>     apply plugin: "eclipse"
>     apply plugin: "idea"
> 
>     version = '1.0'
>     ext {
>         visuiVersion = '1.3.0'
>     }
> }
> 
> project(":core") {
>     apply plugin: "java"
> 
>     dependencies {
>         ...
>         compile "com.kotcrab.vis:vis-ui:$visuiVersion"
>         ...
>     }
> }

**Comment by kotcrab** [comment]
Why did you create exactly the same issue as previous one? You already created #276 where I asked to provide example project if you think this is VisUI issue. Closed issue does not mean you can't respond to it.
Please don't spam the issue tracker.

**Comment by TypeOverride** [comment]
I guess i've forgot it that i already wrote one.... too much in my head at the moment. Sry.
And yeah. I didn't know that i could write on close threads.

You have no clue where to search for, to fix the problem? I've tested some things. But nothing helped. On a new project it isn't work as well. And on other Android Studios or other Java Interpreters.

**Comment by kotcrab** [comment]
Try disabling instant run and use Intellij IDEA. With libGDX you will be testing on desktop most of the time anyways. If newly generated project from official gdx-setup or our [alternative gdx-setup](https://github.com/czyzby/gdx-setup) fails then this is clearly a problem with your setup and not VisUI itself hence the invalid tag and closed issue.

**Comment by TypeOverride** [comment]
You mean use Intelij IDEA and disable instant run, or?
But where is to search the problem? We know now that this is not a VisUI problem. But where is the problem? Do you have a clue?

**Comment by kotcrab** [comment]
> You mean use Intelij IDEA and disable instant run, or?

Both.

I guess the problem is somewhere between Android compiler and its runtime, just google `Android java.lang.NoClassDefFoundError: Failed resolution of`.

>  ... nothing worked. Can't find a fix.

But I just told you a fix you haven't even tried apparently.

**Comment by TypeOverride** [comment]
I gave up. Ive tried everything i can and found. Nothing helped. Fresh project ... nothing change the error.

**Comment by bartekpacia** [comment]
I'm encounterting the same problem. Has anyone found a fix?

**Comment by czyzby** [comment]
@bartekpacia These errors are usually related to the Gradle setup. How did you include the VisUI dependency in your project?

**Comment by bartekpacia** [comment]
Hi @czyzby, thanks for the response and for the library :)

I add `VisUI` as a dependency to project-level `build.gradle` (the one in the project root), like this:

```groovy
project(":core") {
    apply plugin: "java-library"

    dependencies {
        implementation "com.badlogicgames.gdx:gdx:$gdxVersion"

        implementation "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
        implementation "com.kotcrab.vis:vis-ui:$visuiVersion" // visuiVersion = 1.3.0
        implementation "de.golfgl.gdxgamesvcs:gdx-gamesvcs-core:$gamesvcsVersion"
    }
}
```

I was thinking that the problem may be caused by RoboVM performing some optimizations and removing code that is not called directly (and if I'm not mistaken, VisUI does use some reflection), so I tried adding VisUI's classes to `robovm.xml`, like this:

```xml
<config>
  <!-- ... -->
  <forceLinkClasses>
    <!-- ... -->
    <pattern>com.kotcrab.vis.ui.VisUI</pattern> <!-- I also tried some variations like com.kotcrab.vis.**  , etc. -->
  </forceLinkClasses>
```

but it didn't help and I'm out of ideas.

**Comment by czyzby** [comment]
@bartekpacia Try changing your dependencies from `implementation` to `api` in your `build.gradle` files.

> Hi @czyzby, thanks for the response and for the library :)

@kotcrab is the author of the library, I'm just helping with the maintenance. :)
