### ISSUE TITLE
Application crashes when clicking on the first line in TextArea

### ISSUE THREAD

**Issue by Silobrlst** [kotcrab/vis-editor#293]
When I enter a carriage return in TextArea and click on the first line, the application crashes.

VisUI version: 1.3.0

Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: -1
	at com.kotcrab.vis.ui.widget.VisTextArea.letterUnderCursor(VisTextArea.java:108)
	at com.kotcrab.vis.ui.widget.VisTextField$TextFieldClickListener.setCursorPosition(VisTextField.java:1044)
	at com.kotcrab.vis.ui.widget.VisTextArea$TextAreaListener.setCursorPosition(VisTextArea.java:405)
	at com.kotcrab.vis.ui.widget.VisTextField$TextFieldClickListener.touchDown(VisTextField.java:1021)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:147)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchDown(Stage.java:280)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:329)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by thekeenant** [comment]
See: libgdx/libgdx@0273c2288d39777528ece72ffa47c0b8790b42ab

**Comment by Silobrlst** [comment]
Thank you
